language: java

jdk:
- oraclejdk8

script:
- gradle check
- gradle distZip

addons:
  apt:
    packages:
    - oracle-java8-installer
before_install:
- rvm install 2.5.1
- gem install travis-custom-deploy

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

after_success:
- travis-custom-deploy sftp build/distributions/*.zip

env:
  global:
  - secure: gwuoB2JphwCl7ME/RH0opTWTwRLmBl/b/O94qh1zKxezozXkoZI2Fq4Qhe+aO8OHZ4BIptq3KFC940ICd87T5b1ngH5R87CTnuUgYfVWRatKgWu4wL39NT3MvyNCjwmsPk5BiXrF0gQxdnsTOpzIAFQQWsulJibJAdCMjJxri0/tF8uMkhbjqliFpS51rY8pKqSFJDZq+pWpVAhSh8rcarnvRJUgMplQM5Ic3uVjdyEz8NyQlADT2kJ2muafXvYpGRvL95jwvrGipjzmmuwl7adKGXUnAFUD+udm6MIFUnZcwKybzQ9H/7SwH6ieOY8hc06flsdmS5ZLvV7qAx/QIidHfkaTmT94eOAoynYH9CGbvW3FFhWD0mLQZerzLdfQ3+p9Y8jQpH3ekeqaOtH9Ar2GqFuDW3uXFwuu1rYU3O1JOuNH7xMxbxMrjOFESMiQsvB2+k3hVV9hzRtWnGJO3rq7xH5uUU0CowDGRnZbzMsnuBuWM8SUJPTjH6rPPFG4tR6/aqOhpbqLaFkteiN58Ru/qsy9wAnAlOlnFKH7BOW/vH0BYK7yXM5HxN621zyf7X8ZFN/s3JNoP+fdST6yqfIRsVvO2gNBxYmCPUUaINt1qZR9AsDJtoUZRT3m7VsthAPPyu6kAco7pupdrweFQri709BVmCSX4H7fojoSD2w=
  - secure: QqrMtywLYpEqoS8owxiOtcboMgboJzNz+bbpoh02cSWqCLm499XXUWYLvcCMVoVyg63QG9+iI0y1BRipxnFJlh9fY61B07Y2LqLobWyo2wHxvKXuvQuGxBgqcw5NfykEiv9Dx/pNRBD/pmpMivLK95XX2UYk5D3F75ump+sjqtXFDviMkMm8AoPh1eZcEwsRoVzosn845gf9z7oKLsWNXnQMrnyZ8Pdhx7sTWZ5AnQ3sdhF9VWifEHLqqqTSFTyGt/OKRb+mE/AzaifzCAIb8gZYbFdYlh4p58CY3gM38TBIXsPf8hVnwGodA6WzI1gxkC5P4zD7OTFKIR3YVqDUduwo45zM3DTkl1sRyEX0oxsQdB8Dj0TG0uo9qt6dbqSaoBAaGYU9f7qbI17H7fXlp/Z8NvkvdSihjkwsEloqQR6Yr8wG1dBHoOkFqT22xBVCFTcrVgyMj3WDWvTWRpaOWwv7aWIPj8gegY8FU+Xb0R5BydhBavYR7wo2VxSJ49AN9WdY+W+vSZmjRLgVPFS74y+PgO7FZNoNBHe80T6d/JJ4c5I6RpOXVpRFq+mLjDL0/K2YYRhQzLCQ7m5sQwfQgnLxrCkJzpE+1LoGRwvkEwLsmiEbT2qEP0Qlsp8WmVMkup9eUSUV/gdHEgP6DCoCxwawQdZOuL2Wvw9yurcMtuc=
  - secure: Fmd8b9JYCXQx6nmZWFsKqWGvwaLMA0s4tUSnx79aoFlAHq0zKJppVE3hnQYxm3kOf32JnIfDip9q8s7aTLhYPGwJKxl59UOvtxr8hgrdUoTXYCpMVr/5dXrau2Wt6fXG5kMLBVnGBj3fAusfdupAbbrfi6AxNo2ZC4lAibcTr9wQ+Llw1dPDGuS3LQ8XlPJOjcvLizFCkguRlGj0taDo9NNy2hK0tHVT5U9sKMrkkcdlq+swFETtpvfALMg4rw+I9Mqu6Z18WS9mUHXU6xcwY8LbFs0IfHguQvJ6rdEQwcNnPCXlid81mmMZ5sziKF4nVspi8HmbCEg2Y5CtqSZdm0gTxtWeyDRKocKsjqXXtklExFp5CFhdypWfh6cpZ5PCN3bnXOp4fhzODD2YVT3m9se1JeRbQEbqIfuNxTpkcAyZwZZYqeb+53HHN0IzrQmYdt3m+d7Vkg7Sn/ZYCtl4LqbOgS/fD3eF2tKLRxFM8bYn+kx2pMMrGmygQVN2Ef5L7B9GxWaOUlO5rYyw4eggXt8YCHvIBzwjakNgA6ms7BrScXm+yIEAekoDR7mGucHGbyA6Y9uaFSB0M2sf0/tRiiQ9kAgxryiTTcC5kXwaNR0V8URHgBwjGfnZIQSQStKpGzgC70SihSG+Xw0vtUizRq5oxoZ+uTBY3KeMTt0DWhE=
  - secure: SYDbEb31vNRNhEuSKWd716aZuffE4jMy5L8+jyj2kSIlgQTcWyVwZxTC6F+RpubhaTDW93zu4JUkEMC1GwRKjgNmHhmSMXkD89S27+cjNn1sAnTwCIWl6BpZKtOmxq+Ej67xjox+FMyFkq3uNQfdcPPhOpmM15bKldLzFRywLHl0yuoshtNlw3nFxzPxAanCloZ9fmp6twR/pkVIwRku6857HCGAC66PSE6jKDA+NcKyLjyfNYJpmVKmpvHp3lQoxS1hPkG4RreAqI0KmOzH8KfYzHAqL+ucAtc85Q8bbnMUA9dl+UY6qctMmkT6BoRMLtgSPl1ajbabSjHBCXpI/L3IEFo4jnSAajoiYsnj7xCYtx48akB820l9buGspx/JSWG+rapVOvGk1/AcCHDn3OiWZomBdyfytjSmJFhxmlI60ShPSyp7Ew/c408iiqOOBPtWBuR7pLBbv8rvkBD0rf9rx9HfF9AMhag8/ZMn3BPYKjWMOqpgh9WY4fZQ51Qqlbulg857rHyPwEBIpjLDyBYuUcf/GjN3t1CeGdQqbwCGRdKgufdyn6JY/KzXi6og1nc3iEtod/5wvadig6Z9TBTStl8rzSXX8I9t2po+vi6yD1g00i/apbfkzqLW7IThnF27g388tKAnFuqXw/dtS3YhrA4cIt+Dgp4566LD/hY=
